spring:
  redis:
    database: ${redis.database:0}
    host: ${redis.host:localhost}
    password: ${redis.password:qazwsx123!}
    port: ${redis.port:6379}
    jedis:
      pool:
        max-idle: 20
        min-idle: 5
        max-active: 100
        max-wait: 1000ms
